[package]
name = "remi-config"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
remi-core = { workspace = true }
config = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
