[package]
name = "remi-workspace"
version.workspace = true
edition.workspace = true

[dependencies]
remi-core = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
walkdir = { workspace = true }
globset = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
