[package]
name = "remi-workspace"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
remi-core.workspace = true
remi-contracts.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
ignore = "0.4"
chrono.workspace = true
uuid.workspace = true
lru = "0.12"
parking_lot = "0.12"

[dev-dependencies]
tokio-test.workspace = true
tempfile = "3"
