[package]
name = "remi-checkpoint"
version.workspace = true
edition.workspace = true

[dependencies]
remi-core = { workspace = true }
remi-git = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
