/**
 * @fileoverview ACP 协议元数据（自动生成）
 *
 * 定义 ACP 协议中 Agent 端和 Client 端所有 RPC 方法名的常量映射。
 * 此文件由代码生成工具自动生成，请勿手动编辑。
 *
 * 所属模块：effect-acp（自动生成）
 * 主要导出：AGENT_METHODS、CLIENT_METHODS、PROTOCOL_VERSION
 *
 * @see https://agentclientprotocol.com
 */

// This file is generated by the effect-acp package. Do not edit manually.
// Current ACP schema release: v0.11.3

/** Agent 端 RPC 方法名常量 */
export const AGENT_METHODS = {
  /** 认证方法 */
  authenticate: "authenticate",
  /** 初始化方法 */
  initialize: "initialize",
  /** 登出方法 */
  logout: "logout",
  /** 取消会话通知 */
  session_cancel: "session/cancel",
  /** 关闭会话 */
  session_close: "session/close",
  /** 分叉会话 */
  session_fork: "session/fork",
  /** 列出会话 */
  session_list: "session/list",
  /** 加载会话 */
  session_load: "session/load",
  /** 新建会话 */
  session_new: "session/new",
  /** 发送提示 */
  session_prompt: "session/prompt",
  /** 恢复会话 */
  session_resume: "session/resume",
  /** 设置会话配置选项 */
  session_set_config_option: "session/set_config_option",
  /** 设置会话模式 */
  session_set_mode: "session/set_mode",
  /** 设置会话模型 */
  session_set_model: "session/set_model",
} as const;

/** Client 端 RPC 方法名常量 */
export const CLIENT_METHODS = {
  /** 读取文本文件 */
  fs_read_text_file: "fs/read_text_file",
  /** 写入文本文件 */
  fs_write_text_file: "fs/write_text_file",
  /** 引导输入对话 */
  session_elicitation: "session/elicitation",
  /** 引导输入完成通知 */
  session_elicitation_complete: "session/elicitation/complete",
  /** 请求权限 */
  session_request_permission: "session/request_permission",
  /** 会话更新通知 */
  session_update: "session/update",
  /** 创建终端 */
  terminal_create: "terminal/create",
  /** 终止终端 */
  terminal_kill: "terminal/kill",
  /** 终端输出 */
  terminal_output: "terminal/output",
  /** 释放终端 */
  terminal_release: "terminal/release",
  /** 等待终端退出 */
  terminal_wait_for_exit: "terminal/wait_for_exit",
} as const;

/** 当前 ACP 协议版本号 */
export const PROTOCOL_VERSION = 1 as const;
