/**
 * @file Office PPTX 导出工具
 *
 * 封装 `office_pptx_generate` Tauri 命令的前端调用桥，提供：
 * - `planMarkdownToSlides` 把 Plan Markdown 转换为幻灯片描述
 * - `exportSlidesAsPptx` 弹保存对话框并调用后端生成 .pptx
 *
 * 类型契约复用 `contracts/office.ts`，与后端 `commands/office.rs::PptxSlideInput`
 * 通过 `#[serde(rename_all = "camelCase")]` 对齐（camelCase）。
 *
 * ## 使用场景
 *
 * - ProposedPlanActions 中的"导出为 PPT"按钮
 * - 后续 AI Agent 自动把对话内容导出为演示文稿
 *
 * ## 安全注意
 *
 * - 路径来自用户选择的保存对话框，由 Tauri 受控
 * - slides 内容会经 XML 转义（后端 `escape_xml`），防注入
 */

import { save } from "@tauri-apps/plugin-dialog";
import { proposedPlanTitle } from "../proposedPlan";
import { toastManager } from "../components/ui/toast";
import { officePptxGenerate, type PptxSlideInput } from "../contracts/office";

export type { PptxSlideInput };

/** 单张幻灯片最多要点数，避免单页过载 */
const MAX_BULLETS_PER_SLIDE = 8;
/** 单个要点最大字符数，避免溢出幻灯片 */
const MAX_BULLET_LENGTH = 120;
/** 最大幻灯片数，避免生成超长 PPT */
const MAX_SLIDES = 30;
/** 默认副标题（当 plan 无明确副标题时） */
const DEFAULT_SUBTITLE = "Generated by ydsz-buddy";

/**
 * 把 Plan Markdown 转换为幻灯片描述列表
 *
 * 转换规则：
 * 1. 第一张为 title 类型，标题取自 plan 标题，副标题为生成时间
 * 2. 每个 `##` 二级标题转为 section 类型（章节分隔）
 * 3. 二级标题下的 `-` 列表转为 content 类型（标题=二级标题，bullets=列表项）
 * 4. 三级及以下标题忽略，避免幻灯片层级过深
 *
 * @param planMarkdown - 原始 Plan Markdown
 * @returns 幻灯片描述列表（至少 1 张 title 页）
 */
export function planMarkdownToSlides(planMarkdown: string): PptxSlideInput[] {
  const title = proposedPlanTitle(planMarkdown) ?? "云顶数字 Plan";
  const slides: PptxSlideInput[] = [
    {
      slideType: "title",
      title,
      subtitle: `${DEFAULT_SUBTITLE} · ${new Date().toISOString().slice(0, 10)}`,
    },
  ];

  const lines = planMarkdown.split("\n");
  let currentSection = "";
  let currentBullets: string[] = [];

  const flushContentSlide = () => {
    if (currentSection && currentBullets.length > 0) {
      const trimmed = currentBullets
        .map((b) => b.trim())
        .filter((b) => b.length > 0)
        .slice(0, MAX_BULLETS_PER_SLIDE)
        .map((b) => (b.length > MAX_BULLET_LENGTH ? `${b.slice(0, MAX_BULLET_LENGTH - 1)}…` : b));
      if (trimmed.length > 0) {
        slides.push({
          slideType: "content",
          title: currentSection,
          bullets: trimmed,
        });
      }
    }
    currentBullets = [];
  };

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();

    // 二级标题：作为新的章节分隔
    const h2Match = /^##\s+(.+?)\s*$/.exec(line);
    if (h2Match) {
      flushContentSlide();
      currentSection = h2Match[1].trim();
      slides.push({
        slideType: "section",
        title: currentSection,
      });
      continue;
    }

    // 三级及以上标题：忽略，不转为幻灯片
    if (/^#{3,}\s+/.test(line)) {
      continue;
    }

    // 列表项：收集到当前章节
    const bulletMatch = /^[-*+]\s+(.+?)\s*$/.exec(line);
    if (bulletMatch && currentSection) {
      currentBullets.push(bulletMatch[1].trim());
      continue;
    }

    // 有序列表项：同样作为要点
    const orderedMatch = /^\d+\.\s+(.+?)\s*$/.exec(line);
    if (orderedMatch && currentSection) {
      currentBullets.push(orderedMatch[1].trim());
      continue;
    }
  }

  flushContentSlide();

  // 限制最大幻灯片数，超出截断
  if (slides.length > MAX_SLIDES) {
    return slides.slice(0, MAX_SLIDES);
  }

  return slides;
}

/**
 * 导出幻灯片描述为 .pptx 文件
 *
 * 1. 弹保存对话框让用户选择输出路径
 * 2. 调用 `office_pptx_generate` Tauri 命令生成文件
 * 3. 成功/失败均通过 toast 反馈
 *
 * @param slides - 幻灯片描述列表
 * @param defaultFilename - 默认文件名（不含扩展名）
 * @returns 成功导出时返回文件路径，失败或取消时返回 null
 */
export async function exportSlidesAsPptx(
  slides: PptxSlideInput[],
  defaultFilename: string,
): Promise<string | null> {
  if (slides.length === 0) {
    toastManager.add({
      type: "error",
      title: "Cannot export PPT",
      description: "Slides are empty.",
    });
    return null;
  }

  // 1. 弹保存对话框（仅获取路径，不写入内容；二进制 .pptx 由后端命令写入）
  let filePath: string | null;
  try {
    filePath = await save({
      defaultPath: `${defaultFilename}.pptx`,
      filters: [{ name: "PowerPoint", extensions: ["pptx"] }],
    });
  } catch (error) {
    toastManager.add({
      type: "error",
      title: "Could not open save dialog",
      description: error instanceof Error ? error.message : "An error occurred.",
    });
    return null;
  }

  if (!filePath) {
    // 用户取消，不报错
    return null;
  }

  // 2. 调用后端生成命令（写入二进制 .pptx）
  try {
    await officePptxGenerate(filePath, slides);
    toastManager.add({
      type: "success",
      title: "Presentation exported",
      description: filePath,
    });
    return filePath;
  } catch (error) {
    toastManager.add({
      type: "error",
      title: "Could not export PPT",
      description: error instanceof Error ? error.message : String(error),
    });
    return null;
  }
}
