//! Event Store Module
//!
//! This module implements a SQLite-based event store for persisting domain events.
//! The event store is the core component of the Event Sourcing pattern, responsible for:
//! - Appending new events to the event stream
//! - Reading events in sequence order
//! - Tracking event sequence numbers (for projection synchronization)
//!
//! # Design Notes
//!
//! The event store uses append-only mode, all events are sorted by sequence number.
//! Each event contains aggregate root information (aggregate_kind + stream_id) for querying by aggregate.
use async_trait::async_trait;
use remi_core::events::OrchestrationEvent;
use remi_core::models::Sequence;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::error::PersistenceResult;
use crate::sqlite_client::SqliteClient;

/// Event Store trait
///
/// Defines the core interface for event storage. All event store implementations must implement this trait.
/// Uses `async_trait` for async support with `Send + Sync` bounds for thread safety.
///
/// # Main Functions
///
/// - `append_event`: Append an event to the event stream
/// - `read_events`: Read events starting from a specific sequence number
/// - `get_latest_sequence`: Get the current latest sequence number
#[async_trait]
pub trait EventStore: Send + Sync {
    /// Append an event to the event store
    ///
    /// Persists a new event to the database and returns the assigned sequence number.
    /// The sequence number is auto-generated by the database (auto-increment primary key).
    ///
    /// # Parameters
    ///
    /// * `event` - Reference to the orchestration event to append
    ///
    /// # Returns
    ///
    /// Returns the assigned sequence number on success, or `PersistenceError` on failure
    fn append_event(&self, event: &OrchestrationEvent) -> PersistenceResult<Sequence>;

    /// Read events starting from a specific sequence number
    ///
    /// Reads events in ascending sequence order with pagination support.
    /// Read range: `(from_sequence, from_sequence + limit]`, excluding `from_sequence` itself.
    ///
    /// # Parameters
    ///
    /// * `from_sequence` - Starting sequence number (exclusive), reads from after this number
    /// * `limit` - Maximum number of events to return
    ///
    /// # Returns
    ///
    /// Returns a list of `StoredEvent` in ascending sequence order on success.
    /// Returns an empty list if there are no more events.
    fn read_events(&self, from_sequence: Sequence, limit: usize) -> PersistenceResult<Vec<StoredEvent>>;

    /// Get the current latest sequence number
    ///
    /// Returns the maximum sequence number assigned in the event store.
    /// Returns 0 if the event store is empty.
    ///
    /// # Returns
    ///
    /// The current latest sequence number, used by projectors to track processed event positions
    fn get_latest_sequence(&self) -> PersistenceResult<Sequence>;
}

/// Stored Event
///
/// Event data read from the database, containing all metadata and payload.
/// This struct is the raw representation of an event in the database, not yet deserialized into a specific domain event type.
///
/// # Field Descriptions
///
/// - `sequence`: Global event sequence number, used for ordering and synchronization
/// - `event_id`: Event unique identifier (UUID)
/// - `event_type`: Event type name, e.g. 'project.created'
/// - `aggregate_kind`: Aggregate root type, e.g. 'project' or 'thread'
/// - `stream_id`: Event stream ID (unique identifier of the aggregate root)
/// - `payload_json`: JSON-serialized event payload
/// - `metadata_json`: Additional event metadata (optional)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoredEvent {
    /// Event sequence number, globally unique and incrementing
    pub sequence: Sequence,
    /// Event unique identifier
    pub event_id: String,
    /// Event type name
    pub event_type: String,
    /// Aggregate root type
    pub aggregate_kind: String,
    /// Event stream ID (unique identifier of the aggregate root)
    pub stream_id: String,
    /// Stream version
    pub stream_version: i64,
    /// Event payload (JSON format)
    pub payload_json: String,
    /// Event occurrence timestamp
    pub occurred_at: String,
    /// Triggering command ID (optional)
    pub command_id: Option<String>,
    /// Causation event ID (optional)
    pub causation_event_id: Option<String>,
    /// Correlation ID (optional)
    pub correlation_id: Option<String>,
    /// Actor kind
    pub actor_kind: String,
    /// Event metadata (JSON format)
    pub metadata_json: String,
}

/// SQLite Event Store Implementation
///
/// Event store implementation based on SQLite database, providing event persistence and query capabilities.
/// Uses `SqliteClient` internally for database operations.
pub struct SqliteEventStore {
    /// SQLite database client
    client: SqliteClient,
}

impl SqliteEventStore {
    /// Create a new SQLite event store instance
    ///
    /// # Parameters
    ///
    /// * `client` - Initialized SQLite client instance
    ///
    /// # Returns
    ///
    /// Returns a newly created `SqliteEventStore` instance
    pub fn new(client: SqliteClient) -> Self {
        Self { client }
    }

    /// Extract aggregate root information from an event
    ///
    /// Extracts the aggregate root type, event stream ID, and event type name based on the event type.
    /// This is a key helper method for the event store, used to map domain events to database storage format.
    ///
    /// # Parameters
    ///
    /// * `event` - Reference to the orchestration event
    ///
    /// # Returns
    ///
    /// Returns a tuple `(aggregate_kind, stream_id, event_type)`
    /// - `aggregate_kind`: Aggregate root type (e.g. 'project' or 'thread')
    /// - `stream_id`: Event stream ID (unique identifier of the aggregate root)
    /// - `event_type`: Event type name (e.g. 'project.created' or 'thread.created')
    ///
    /// # Implementation Notes
    ///
    /// Uses pattern matching to iterate through all event variants and extract the corresponding aggregate root information.
    /// Event type names follow the 'aggregate.action' naming convention, e.g. 'project.created'
    fn extract_aggregate_info(event: &OrchestrationEvent) -> (String, String, String) {
        match event {
            // Project-related events
            OrchestrationEvent::ProjectCreated(e) => ("project".to_string(), e.project_id.to_string(), "project.created".to_string()),
            OrchestrationEvent::ProjectMetaUpdated(e) => ("project".to_string(), e.project_id.to_string(), "project.meta-updated".to_string()),
            OrchestrationEvent::ProjectDeleted(e) => ("project".to_string(), e.project_id.to_string(), "project.deleted".to_string()),
            // Thread-related events
            OrchestrationEvent::ThreadCreated(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.created".to_string()),
            OrchestrationEvent::ThreadDeleted(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.deleted".to_string()),
            OrchestrationEvent::ThreadArchived(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.archived".to_string()),
            OrchestrationEvent::ThreadUnarchived(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.unarchived".to_string()),
            OrchestrationEvent::ThreadMetaUpdated(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.meta-updated".to_string()),
            OrchestrationEvent::ThreadRuntimeModeSet(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.runtime-mode-set".to_string()),
            OrchestrationEvent::ThreadInteractionModeSet(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.interaction-mode-set".to_string()),
            OrchestrationEvent::ThreadMessageSent(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.message-sent".to_string()),
            OrchestrationEvent::ThreadTurnQueued(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.turn-queued".to_string()),
            OrchestrationEvent::ThreadTurnStartRequested(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.turn-start-requested".to_string()),
            OrchestrationEvent::ThreadTurnInterruptRequested(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.turn-interrupt-requested".to_string()),
            OrchestrationEvent::ThreadApprovalResponseRequested(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.approval-response-requested".to_string()),
            OrchestrationEvent::ThreadUserInputResponseRequested(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.user-input-response-requested".to_string()),
            OrchestrationEvent::ThreadCheckpointRevertRequested(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.checkpoint-revert-requested".to_string()),
            OrchestrationEvent::ThreadReverted(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.reverted".to_string()),
            OrchestrationEvent::ThreadTurnDiffCompleted(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.turn-diff-completed".to_string()),
            OrchestrationEvent::ThreadConversationRollbackRequested(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.conversation-rollback-requested".to_string()),
            OrchestrationEvent::ThreadConversationRolledBack(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.conversation-rolled-back".to_string()),
            OrchestrationEvent::ThreadMessageEditResendRequested(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.message-edit-resend-requested".to_string()),
            OrchestrationEvent::ThreadSessionStopRequested(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.session-stop-requested".to_string()),
            OrchestrationEvent::ThreadSessionSet(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.session-set".to_string()),
            OrchestrationEvent::ThreadProposedPlanUpserted(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.proposed-plan-upserted".to_string()),
            OrchestrationEvent::ThreadActivityAppended(e) => ("thread".to_string(), e.thread_id.to_string(), "thread.activity-appended".to_string()),
        }
    }
}

impl EventStore for SqliteEventStore {
    /// Append an event to the event store
    ///
    /// Implementation steps:
    /// 1. Generate a unique event ID (UUID v4)
    /// 2. Extract aggregate root information (type, stream ID, event type name)
    /// 3. Serialize the event to JSON format
    /// 4. Insert into database, sequence number is auto-generated by the database
    /// 5. Get and return the last inserted sequence number
    fn append_event(&self, event: &OrchestrationEvent) -> PersistenceResult<Sequence> {
        // Generate a unique event identifier
        let event_id = Uuid::new_v4().to_string();
        // Extract aggregate root information and event type
        let (aggregate_kind, stream_id, event_type) = Self::extract_aggregate_info(event);
        // Serialize the event to JSON string
        let payload_json = serde_json::to_string(event)?;
        // Get event occurrence time and convert to RFC3339 format
        let occurred_at = event.occurred_at().to_rfc3339();
        // Get the command ID that triggered this event (if any)
        let command_id = event.command_id();
        // Set default values (these fields do not exist in the current event structure, using reasonable defaults)
        let stream_version = 0;
        let causation_event_id: Option<String> = None;
        let correlation_id: Option<String> = None;
        let actor_kind = "system".to_string();
        let metadata_json = "{}".to_string();

        // Execute the insert operation
        self.client.execute(
            "INSERT INTO orchestration_events (event_id, aggregate_kind, stream_id, stream_version, event_type, occurred_at, command_id, causation_event_id, correlation_id, actor_kind, payload_json, metadata_json)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)",
            &[
                &event_id,
                &aggregate_kind,
                &stream_id,
                &stream_version.to_string(),
                &event_type,
                &occurred_at,
                &command_id,
                &causation_event_id,
                &correlation_id,
                &actor_kind,
                &payload_json,
                &metadata_json,
            ],
        )?;

        // Get the auto-generated sequence number from the database
        let sequence = self.client.last_insert_rowid()? as Sequence;
        Ok(sequence)
    }

    /// Read events starting from a specific sequence number
    ///
    /// Implementation steps:
    /// 1. Build query to filter events with sequence number greater than `from_sequence`
    /// 2. Sort by sequence number in ascending order
    /// 3. Limit the number of returned results to `limit`
    /// 4. Map each row to a `StoredEvent` struct
    fn read_events(&self, from_sequence: Sequence, limit: usize) -> PersistenceResult<Vec<StoredEvent>> {
        let rows = self.client.query_map(
            "SELECT sequence, event_id, event_type, aggregate_kind, stream_id, stream_version, payload_json, occurred_at, command_id, causation_event_id, correlation_id, actor_kind, metadata_json
             FROM orchestration_events
             WHERE sequence > ?1
             ORDER BY sequence ASC
             LIMIT ?2",
            &[&from_sequence, &(limit as i64)],
            |row| {
                // Map database row to StoredEvent struct
                Ok(StoredEvent {
                    sequence: row.get(0)?,
                    event_id: row.get(1)?,
                    event_type: row.get(2)?,
                    aggregate_kind: row.get(3)?,
                    stream_id: row.get(4)?,
                    stream_version: row.get(5)?,
                    payload_json: row.get(6)?,
                    occurred_at: row.get(7)?,
                    command_id: row.get(8)?,
                    causation_event_id: row.get(9)?,
                    correlation_id: row.get(10)?,
                    actor_kind: row.get(11)?,
                    metadata_json: row.get(12)?,
                })
            },
        )?;

        Ok(rows)
    }

    /// Get the current latest sequence number
    ///
    /// Uses `MAX(sequence)` to query the maximum sequence number, returns 0 if the table is empty.
    /// The `COALESCE` function ensures that 0 is returned instead of NULL even when there is no data.
    fn get_latest_sequence(&self) -> PersistenceResult<Sequence> {
        let sequence: Sequence = self.client.query_row(
            "SELECT COALESCE(MAX(sequence), 0) FROM orchestration_events",
            &[],
            |row| row.get(0),
        )?;

        Ok(sequence)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::migrations::run_migrations;
    use chrono::Utc;
    use remi_core::events::{ProjectCreatedEvent, ThreadCreatedEvent, OrchestrationEvent};
    use remi_core::models::ProjectId;

    /// Helper function: create a temporary database
    fn make_test_db(test_name: &str) -> (SqliteClient, std::path::PathBuf) {
        let temp_dir = std::env::temp_dir().join(format!("remi-test-event-store-{}", test_name));
        let _ = std::fs::remove_dir_all(&temp_dir);
        let db_path = temp_dir.join("test.sqlite");
        let client = SqliteClient::new(&db_path).unwrap();
        run_migrations(&client).unwrap();
        (client, temp_dir)
    }

    #[test]
    fn test_event_store() {
        let (client, temp_dir) = make_test_db("basic");

        let store = SqliteEventStore::new(client);

        // Create test event
        let event = OrchestrationEvent::ProjectCreated(ProjectCreatedEvent {
            sequence: 0,
            occurred_at: Utc::now(),
            command_id: None,
            project_id: ProjectId::new_v4(),
            title: "Test Project".to_string(),
            workspace_root: "/tmp/test".to_string(),
        });

        // Append event
        let seq = store.append_event(&event).unwrap();
        assert_eq!(seq, 1);

        // Read events
        let events = store.read_events(0, 10).unwrap();
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].sequence, 1);

        // Get latest sequence number
        let latest = store.get_latest_sequence().unwrap();
        assert_eq!(latest, 1);

        // Cleanup
        let _ = std::fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_event_store_empty_initial_latest_is_zero() {
        let (client, temp_dir) = make_test_db("empty");
        let store = SqliteEventStore::new(client);

        // Empty table should return 0
        assert_eq!(store.get_latest_sequence().unwrap(), 0);
        assert!(store.read_events(0, 10).unwrap().is_empty());

        let _ = std::fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_event_store_sequential_appends() {
        let (client, temp_dir) = make_test_db("sequential");
        let store = SqliteEventStore::new(client);

        for i in 0..5 {
            let ev = OrchestrationEvent::ProjectCreated(ProjectCreatedEvent {
                sequence: 0,
                occurred_at: Utc::now(),
                command_id: None,
                project_id: ProjectId::new_v4(),
                title: format!("Project-{}", i),
                workspace_root: "/tmp".to_string(),
            });
            let seq = store.append_event(&ev).unwrap();
            assert_eq!(seq, (i + 1) as u64);
        }

        assert_eq!(store.get_latest_sequence().unwrap(), 5);
        let events = store.read_events(0, 100).unwrap();
        assert_eq!(events.len(), 5);
        // Sequence should be in ascending order
        for (i, e) in events.iter().enumerate() {
            assert_eq!(e.sequence, (i + 1) as u64);
        }

        let _ = std::fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_event_store_pagination_from_sequence() {
        let (client, temp_dir) = make_test_db("pagination");
        let store = SqliteEventStore::new(client);

        for i in 0..10 {
            let ev = OrchestrationEvent::ProjectCreated(ProjectCreatedEvent {
                sequence: 0,
                occurred_at: Utc::now(),
                command_id: None,
                project_id: ProjectId::new_v4(),
                title: format!("Project-{}", i),
                workspace_root: "/tmp".to_string(),
            });
            store.append_event(&ev).unwrap();
        }

        // Read 3 events after sequence number 5
        let page = store.read_events(5, 3).unwrap();
        assert_eq!(page.len(), 3);
        assert_eq!(page[0].sequence, 6);
        assert_eq!(page[2].sequence, 8);

        // Out of range
        let empty = store.read_events(10, 5).unwrap();
        assert!(empty.is_empty());

        let _ = std::fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_event_store_aggregate_info_extraction() {
        let (client, temp_dir) = make_test_db("aggregate-info");
        let store = SqliteEventStore::new(client);

        // Thread events should be classified under thread aggregate
        let project_id = ProjectId::new_v4();
        let thread_id = remi_core::models::ThreadId::new_v4();

        let ev = OrchestrationEvent::ThreadCreated(Box::new(ThreadCreatedEvent {
            sequence: 0,
            occurred_at: Utc::now(),
            command_id: Some("cmd-x".to_string()),
            thread_id,
            project_id,
            title: "T".to_string(),
            model_selection: remi_core::provider::ModelSelection {
                provider: remi_core::provider::ProviderKind::Codex,
                model: "gpt-5".to_string(),
                options: None,
            },
            runtime_mode: remi_core::models::RuntimeMode::Code,
            interaction_mode: remi_core::models::InteractionMode::Agent,
            env_mode: remi_core::models::EnvMode::Local,
            branch: None,
            worktree_path: None,
            associated_worktree: None,
            is_pinned: false,
            parent_thread_id: None,
            subagent: None,
            fork_source_thread_id: None,
            sidechat_source_thread_id: None,
            last_known_pr: None,
            handoff: None,
        }));
        let seq = store.append_event(&ev).unwrap();

        let stored = store.read_events(0, 10).unwrap();
        assert_eq!(stored.len(), 1);
        let s = &stored[0];
        assert_eq!(s.sequence, seq);
        assert_eq!(s.aggregate_kind, "thread");
        assert_eq!(s.stream_id, thread_id.to_string());
        assert_eq!(s.event_type, "thread.created");
        assert_eq!(s.command_id.as_deref(), Some("cmd-x"));
        assert!(!s.payload_json.is_empty());

        let _ = std::fs::remove_dir_all(&temp_dir);
    }
}

