// This file has been generated by Specta. Do not edit this file manually.
/**  捕获项：S-expression 查询中 `@name` 节点对应的文本 */
export type AstGrepCapture = {
	/**  捕获名 */
	name: string,
	/**  捕获文本 */
	text: string,
};

/**  `indexer.astGrepCompilePattern` 输入 */
export type AstGrepCompilePatternInput = {
	/**  目标语言 */
	language: AstGrepLanguage,
	/**  用户友好的模式（如 `"console.log($MSG)"` / `"call_expression"`） */
	pattern: string,
};

/**  模式编译结果 */
export type AstGrepCompiledPattern = {
	/**  tree-sitter S-expression */
	query: string,
	/**  顶层 capture 名（按出现顺序） */
	captures: string[],
};

/**  `indexer.astGrepFindByName` 输入（统一 find_references + find_calls_to 入口） */
export type AstGrepFindByNameInput = {
	/**  工作区根目录 */
	workspace_root: string,
	/**  名称（支持 `"foo"` / `"obj.foo"` 两种形式） */
	name: string,
	/**  `references`：找所有标识符出现位置；`calls`：仅找 `name(...)` 形式调用 */
	mode?: AstGrepFindMode,
};

/**  `indexer.astGrepFindByNodeKind` 输入 */
export type AstGrepFindByNodeKindInput = {
	/**  工作区根目录 */
	workspace_root: string,
	/**  节点类型，如 `try_statement` / `call_expression` / `await_expression` */
	kind: string,
};

/**  `indexer.astGrepFindByQuery` 输入 */
export type AstGrepFindByQueryInput = {
	/**  工作区根目录 */
	workspace_root: string,
	/**  目标语言 */
	language: AstGrepLanguage,
	/**  S-expression 查询字符串 */
	query: string,
};

/**  `astGrepFindByName` 检索模式 */
export type AstGrepFindMode = 
/**  找 `name(...)` 形式的调用 */
"calls" | 
/**  找所有 `name` 标识符出现位置（含定义、调用、读取等） */
"references";

/**  AST-Grep 支持的目标语言 */
export type AstGrepLanguage = "typescript" | "javascript" | "rust" | "python";

/**  `indexer.astGrepListPresets` 输入（无字段） */
export type AstGrepListPresetsInput = {
	/**  仅返回支持目标语言的 preset（None 表示全部） */
	language?: AstGrepLanguage | null,
};

/**  单条匹配命中 */
export type AstGrepMatch = {
	/**  命中的源文件（绝对路径或相对工作区根） */
	file: string,
	/**  起始行（1-based） */
	line: number,
	/**  起始列（1-based） */
	column: number,
	/**  起始字节偏移 */
	start_byte: number,
	/**  结束字节偏移 */
	end_byte: number,
	/**  命中的原始文本 */
	text: string,
	/**  命中的节点类型 */
	node_kind: string,
	/**  捕获名 → 文本（仅 S-expression 查询使用） */
	captures?: AstGrepCapture[],
};

/**  AST-Grep 预设模式（与 Rust 端 `ydsz_code::indexer::ast_grep::presets::Preset` 1:1 对应） */
export type AstGrepPreset = 
/**  所有 `console.log(...)` 调用 */
"console_log" | 
/**  所有 `console.error(...)` 调用 */
"console_error" | 
/**  所有 `await fetch(...)` 调用 */
"await_fetch" | 
/**  所有 `try { ... } catch { ... }` 语句 */
"try_catch" | 
/**  所有 `TODO(...)` / `FIXME(...)` 注释 */
"todo_comment" | 
/**  Rust: 所有 `unwrap()` 调用 */
"rust_unwrap" | 
/**  Rust: 所有 `expect("...")` 调用 */
"rust_expect" | 
/**  Python: 所有 `print(...)` 调用 */
"py_print" | 
/**  Python: 所有 `except:` 异常处理 */
"py_except";

/**  AST-Grep 预设模式详情（展示在 UI 的下拉列表中） */
export type AstGrepPresetInfo = {
	/**  preset id（snake_case） */
	id: AstGrepPreset,
	/**  人类可读名 */
	display_name: string,
	/**  支持的语言列表（"typescript" / "javascript" / "rust" / "python"） */
	supported_languages: string[],
};

/**  `indexer.astGrepRewrite` 输入 */
export type AstGrepRewriteInput = AstGrepRewriteInput_Serialize | AstGrepRewriteInput_Deserialize;

/**  `indexer.astGrepRewrite` 输入 */
export type AstGrepRewriteInput_Deserialize = {
	/**  目标文件路径（绝对路径或相对工作区根） */
	file_path: string,
	/**  目标语言 */
	language: AstGrepLanguage,
	/**  匹配模式 */
	pattern: string,
	/**  替换模板（支持 `$NAME` / `$$$BODY` 透传） */
	rewrite: string,
	/**
	 *  是否仅预览不落盘（默认 false，保持向后兼容）
	 * 
	 *  - `None` / `Some(false)`：替换后直接写回文件（旧行为）
	 *  - `Some(true)`：仅返回 `new_content`，不写盘，由调用方决定是否落盘
	 */
	dry_run?: boolean | null,
};

/**  `indexer.astGrepRewrite` 输入 */
export type AstGrepRewriteInput_Serialize = {
	/**  目标文件路径（绝对路径或相对工作区根） */
	file_path: string,
	/**  目标语言 */
	language: AstGrepLanguage,
	/**  匹配模式 */
	pattern: string,
	/**  替换模板（支持 `$NAME` / `$$$BODY` 透传） */
	rewrite: string,
	/**
	 *  是否仅预览不落盘（默认 false，保持向后兼容）
	 * 
	 *  - `None` / `Some(false)`：替换后直接写回文件（旧行为）
	 *  - `Some(true)`：仅返回 `new_content`，不写盘，由调用方决定是否落盘
	 */
	dry_run?: boolean | null,
};

/**  单次替换位置 */
export type AstGrepRewriteLocation = {
	file: string,
	line: number,
	column: number,
};

/**  替换结果 */
export type AstGrepRewriteResult = {
	/**  替换后的完整内容 */
	new_content: string,
	/**  实际替换的次数 */
	replacements: number,
	/**  命中的位置（file:line:column）— 用于 UI 展示 */
	match_locations: AstGrepRewriteLocation[],
};
