// This file has been generated by Specta. Do not edit this file manually.
/**  访问快照 */
export type AuthAccessSnapshot = AuthAccessSnapshot_Serialize | AuthAccessSnapshot_Deserialize;

/**  访问快照 */
export type AuthAccessSnapshot_Deserialize = {
	pairingLinks: AuthPairingLink_Deserialize[],
	clientSessions: AuthClientSession_Deserialize[],
};

/**  访问快照 */
export type AuthAccessSnapshot_Serialize = {
	pairingLinks: AuthPairingLink_Serialize[],
	clientSessions: AuthClientSession_Serialize[],
};

/**  Bearer 引导认证结果 */
export type AuthBearerBootstrapResult = {
	authenticated: boolean,
	role: AuthSessionRole,
	sessionMethod: ServerAuthSessionMethod,
	expiresAt: string,
	sessionToken: string,
};

/**  引导认证输入 */
export type AuthBootstrapInput = {
	credential: string,
};

/**  引导认证结果 */
export type AuthBootstrapResult = {
	/**  固定为 `true`，TS 用 `Schema.Literal(true)` 收紧类型 */
	authenticated: boolean,
	role: AuthSessionRole,
	sessionMethod: ServerAuthSessionMethod,
	/**  ISO 8601 / RFC 3339 字符串 */
	expiresAt: string,
};

/**  客户端元数据 */
export type AuthClientMetadata = AuthClientMetadata_Serialize | AuthClientMetadata_Deserialize;

/**  客户端设备类型 */
export type AuthClientMetadataDeviceType = "desktop" | "mobile" | "tablet" | "bot" | "unknown";

/**  客户端元数据 */
export type AuthClientMetadata_Deserialize = {
	label?: string | null,
	ipAddress?: string | null,
	userAgent?: string | null,
	deviceType: AuthClientMetadataDeviceType,
	os?: string | null,
	browser?: string | null,
};

/**  客户端元数据 */
export type AuthClientMetadata_Serialize = {
	label?: string | null,
	ipAddress?: string | null,
	userAgent?: string | null,
	deviceType: AuthClientMetadataDeviceType,
	os?: string | null,
	browser?: string | null,
};

/**  客户端会话 */
export type AuthClientSession = AuthClientSession_Serialize | AuthClientSession_Deserialize;

/**  客户端会话 */
export type AuthClientSession_Deserialize = {
	sessionId: string,
	subject: string,
	role: AuthSessionRole,
	method: ServerAuthSessionMethod,
	client: AuthClientMetadata_Deserialize,
	issuedAt: string,
	expiresAt: string,
	lastConnectedAt: string | null,
	connected: boolean,
	current: boolean,
};

/**  客户端会话 */
export type AuthClientSession_Serialize = {
	sessionId: string,
	subject: string,
	role: AuthSessionRole,
	method: ServerAuthSessionMethod,
	client: AuthClientMetadata_Serialize,
	issuedAt: string,
	expiresAt: string,
	lastConnectedAt: string | null,
	connected: boolean,
	current: boolean,
};

/**  创建配对凭证输入 */
export type AuthCreatePairingCredentialInput = AuthCreatePairingCredentialInput_Serialize | AuthCreatePairingCredentialInput_Deserialize;

/**  创建配对凭证输入 */
export type AuthCreatePairingCredentialInput_Deserialize = {
	label?: string | null,
};

/**  创建配对凭证输入 */
export type AuthCreatePairingCredentialInput_Serialize = {
	label?: string | null,
};

/**  配对凭证结果 */
export type AuthPairingCredentialResult = AuthPairingCredentialResult_Serialize | AuthPairingCredentialResult_Deserialize;

/**  配对凭证结果 */
export type AuthPairingCredentialResult_Deserialize = {
	id: string,
	credential: string,
	label?: string | null,
	expiresAt: string,
};

/**  配对凭证结果 */
export type AuthPairingCredentialResult_Serialize = {
	id: string,
	credential: string,
	label?: string | null,
	expiresAt: string,
};

/**  配对链接 */
export type AuthPairingLink = AuthPairingLink_Serialize | AuthPairingLink_Deserialize;

/**  配对链接 */
export type AuthPairingLink_Deserialize = {
	id: string,
	credential: string,
	role: AuthSessionRole,
	subject: string,
	label?: string | null,
	createdAt: string,
	expiresAt: string,
};

/**  配对链接 */
export type AuthPairingLink_Serialize = {
	id: string,
	credential: string,
	role: AuthSessionRole,
	subject: string,
	label?: string | null,
	createdAt: string,
	expiresAt: string,
};

/**  撤销客户端会话输入 */
export type AuthRevokeClientSessionInput = {
	sessionId: string,
};

/**  撤销配对链接输入 */
export type AuthRevokePairingLinkInput = {
	id: string,
};

/**  会话角色 */
export type AuthSessionRole = "owner" | "client";

/**  当前会话状态 */
export type AuthSessionState = AuthSessionState_Serialize | AuthSessionState_Deserialize;

/**  当前会话状态 */
export type AuthSessionState_Deserialize = {
	authenticated: boolean,
	auth: ServerAuthDescriptor,
	role?: AuthSessionRole | null,
	sessionMethod?: ServerAuthSessionMethod | null,
	expiresAt?: string | null,
};

/**  当前会话状态 */
export type AuthSessionState_Serialize = {
	authenticated: boolean,
	auth: ServerAuthDescriptor,
	role?: AuthSessionRole | null,
	sessionMethod?: ServerAuthSessionMethod | null,
	expiresAt?: string | null,
};

/**  WebSocket 令牌结果 */
export type AuthWebSocketTokenResult = {
	token: string,
	expiresAt: string,
};

/**  引导认证方式 */
export type ServerAuthBootstrapMethod = "desktop-bootstrap" | "one-time-token";

/**  服务端认证描述符 */
export type ServerAuthDescriptor = {
	policy: ServerAuthPolicy,
	bootstrapMethods: ServerAuthBootstrapMethod[],
	sessionMethods: ServerAuthSessionMethod[],
	sessionCookieName: string,
};

/**  服务端认证策略 */
export type ServerAuthPolicy = "desktop-managed-local" | "loopback-browser" | "remote-reachable" | "unsafe-no-auth";

/**  会话认证方式 */
export type ServerAuthSessionMethod = "browser-session-cookie" | "bearer-session-token";
