// This file has been generated by Specta. Do not edit this file manually.
/**
 *  编辑器唯一标识
 * 
 *  TS 端的 `EditorId` 是 `Schema.Literal(...EDITORS.map((e) => e.id))`，
 *  即从 `EDITORS` 常量数组里取所有 `id`。Rust 端以字符串字面量枚举表示，
 *  运行时接受任何与下方常量值匹配的字符串。
 */
export type EditorId = string;

/**
 *  编辑器启动方式
 * 
 *  - `direct-path`：直接打开文件
 *  - `goto`：`file:line:column` 形式
 *  - `line-column`：行列号分别传
 */
export type EditorLaunchStyle = "direct-path" | "goto" | "line-column";

/**
 *  在编辑器中打开文件的输入
 * 
 *  与 TS 端 `OpenInEditorInput` 同构。
 */
export type OpenInEditorInput = {
	/**  工作目录 */
	cwd: string,
	/**  编辑器 id */
	editor: EditorId,
};
