// This file has been generated by Specta. Do not edit this file manually.
/**  已安装 Skill 元数据 */
export type InstalledSkill = {
	/**  Skill 名称（作为主键） */
	name: string,
	/**  版本 */
	version: string,
	/**  描述 */
	description: string,
	/**  作者 */
	author: string,
	/**  运行时 */
	runtime: string,
	/**  标签 */
	tags: string[],
	/**  依赖 */
	depends: string[],
	/**  安装目录 */
	installDir: string,
	/**  安装时间（Unix 秒字符串） */
	installedAt: string,
	/**  安装源（local:... / github:owner/repo@ref / marketplace:slug） */
	installSource: string,
};

/**  市场分类 */
export type MarketplaceCategory = {
	/**  分类 id（"all" / "verified" / "runtime:code" / "tag:react"） */
	id: string,
	/**  人类可读名 */
	label: string,
	/**  该分类下 skill 数量 */
	count: number | null,
};

/**  市场条目 */
export type MarketplaceEntry = {
	/**  短 slug（marketplace:slug URI 用） */
	slug: string,
	/**  人类可读名 */
	name: string,
	/**  描述 */
	description: string,
	/**  GitHub owner */
	githubOwner: string,
	/**  GitHub repo */
	githubRepo: string,
	/**  GitHub ref（tag / branch / sha） */
	githubRef: string,
	/**  标签 */
	tags: string[],
	/**  运行时（code / work / any） */
	runtime: string,
	/**  是否官方认证 */
	verified: boolean,
};

/**  Skill 的 prompt body（注入 LLM 上下文） */
export type SkillBody = {
	name: string,
	body: string,
	description: string,
	tags: string[],
};

/**  skill install 输入 */
export type SkillInstallInput = {
	source: string,
};

/**  marketplace 搜索输入 */
export type SkillMarketplaceSearchInput = SkillMarketplaceSearchInput_Serialize | SkillMarketplaceSearchInput_Deserialize;

/**  marketplace 搜索输入 */
export type SkillMarketplaceSearchInput_Deserialize = {
	query: string,
	category?: string | null,
};

/**  marketplace 搜索输入 */
export type SkillMarketplaceSearchInput_Serialize = {
	query: string,
	category?: string | null,
};

/**  marketplace trending 输入 */
export type SkillMarketplaceTrendingInput = SkillMarketplaceTrendingInput_Serialize | SkillMarketplaceTrendingInput_Deserialize;

/**  marketplace trending 输入 */
export type SkillMarketplaceTrendingInput_Deserialize = {
	limit?: number | null,
};

/**  marketplace trending 输入 */
export type SkillMarketplaceTrendingInput_Serialize = {
	limit?: number | null,
};

/**  自定义 Skill 模板（前端表单 → 后端 SKILL.md） */
export type SkillTemplate = SkillTemplate_Serialize | SkillTemplate_Deserialize;

/**  自定义 Skill 模板（前端表单 → 后端 SKILL.md） */
export type SkillTemplate_Deserialize = {
	/**  Skill 名称（小写字母/数字/_/-，1-40 字符） */
	name: string,
	/**  版本（默认 "0.0.0"） */
	version?: string | null,
	/**  描述 */
	description?: string | null,
	/**  作者 */
	author?: string | null,
	/**  运行时（code / work / any，默认 "any"） */
	runtime?: string | null,
	/**  标签 */
	tags?: string[] | null,
	/**  依赖 */
	depends?: string[] | null,
	/**  SKILL.md 正文（prompt 模板） */
	body?: string | null,
};

/**  自定义 Skill 模板（前端表单 → 后端 SKILL.md） */
export type SkillTemplate_Serialize = {
	/**  Skill 名称（小写字母/数字/_/-，1-40 字符） */
	name: string,
	/**  版本（默认 "0.0.0"） */
	version?: string | null,
	/**  描述 */
	description?: string | null,
	/**  作者 */
	author?: string | null,
	/**  运行时（code / work / any，默认 "any"） */
	runtime?: string | null,
	/**  标签 */
	tags?: string[] | null,
	/**  依赖 */
	depends?: string[] | null,
	/**  SKILL.md 正文（prompt 模板） */
	body?: string | null,
};
