// This file has been generated by Specta. Do not edit this file manually.
/**
 *  SSH 认证方式（wire-format）
 * 
 *  采用 `#[serde(tag = "type")]` 内部标签格式：
 *  - `{ type: "password", password: "..." }`
 *  - `{ type: "key", keyPath: "...", passphrase: "..." }`
 */
export type SshAuthParams = { type: "password"; password: string } | { type: "key"; keyPath: string; passphrase: string | null };

/**  SSH 连接配置请求（`ssh_connect` 命令入参） */
export type SshConnectParams = {
	host: string,
	port?: number,
	username: string,
	auth: SshAuthParams,
	autoReconnect?: boolean,
};

/**
 *  SSH 连接状态
 * 
 *  对齐 TS 字面量联合类型 `"Disconnected" | "Connecting" | "Connected" | "Reconnecting"`。
 */
export type SshConnectionState = "Disconnected" | "Connecting" | "Connected" | "Reconnecting";

/**  SSH 连接状态响应 */
export type SshConnectionStatusView = {
	state: SshConnectionState,
	connectionId: string | null,
	host: string,
	port: number,
	username: string,
};

/**  `ssh_create_directory` 命令入参 */
export type SshCreateDirectoryParams = {
	connectionId: string,
	path: string,
	recursive?: boolean,
};

/**  `ssh_delete_directory` 命令入参 */
export type SshDeleteDirectoryParams = {
	connectionId: string,
	path: string,
	recursive?: boolean,
};

/**  `ssh_write_file` 命令入参 */
export type SshWriteFileParams = {
	connectionId: string,
	path: string,
	content: string,
	createDirectories?: boolean,
};
