[package]
name = "remi-terminal"
version.workspace = true
edition.workspace = true

[dependencies]
remi-core = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
portable-pty = { workspace = true }
